### ISSUE TITLE
ReportViewer Not Showing Report in Chrome

### ISSUE THREAD

**Issue by dawie** [ilich/MvcReportViewer#124]
I encountered an issue where the report content would not display up in Chrome. The toolbar would display, but not the content of the report.

After looking into it, I found this article that described my issue exactly: http://stackoverflow.com/questions/5428017/cannot-view-ssrs-2008-r2-ssrs-2012-reports-in-safari-chrome-but-works-fine-in

My control name was "ReportViewer_ctl09" and I could resolve the issue by adding the following bit of Javascript to MVCREportViewer.js:

 //DSMIT Fix Visibility in Chrome
        var element = document.getElementById("ReportViewer_ctl09");
        if (element) {
            element.style.overflow = "visible";
        }

I am on the latest version of MvcReportViewer and SSRS 2012.

**Comment by ilich** [comment]
Thank you for the report. I fixed the issue in https://github.com/ilich/MvcReportViewer/issues/120, but the fix was little bit different. You can update MvcReportViewer to the latest version or keep using your fix. It looks good.

**Comment by dawie** [comment]
Just so you know I am on 0.7.3 and it DID NOT Fix the issue for me. I saw issue #120 and updated to the latest version.

The only way I could resolve it was with my fix.

**Comment by ilich** [comment]
Could you send me sample code how you use MvcReportViewer, please? I'd like to add your fix and the test case.

Thank you for supporting the project!

**Comment by dawie** [comment]
It's really simple:

@Html.MvcReportViewer(
                            "/IMSReports/KeyDates",
                        new { reportCompany = 3 },
                        new { Height = "900px", Width = "100%", style = "border: none", scrolling = "yes" })

**Comment by ilich** [comment]
The issue is related to "900px". Back-end code cannot parse a number from the string and apply required adjustments. The fix is coming soon.

**Comment by ilich** [comment]
Please install MvcReportViewer 0.7.4
